### ISSUE TITLE
Intermittent connection failures

### ISSUE THREAD

**Issue by konomith** [CleverCloud/lapin#324]
Hello, thank you for the great crate!

I've been facing intermittent connection failures when using `Connection::connect`. I cannot post the full code, but here's how the connection is established:
```rust
// _connect is a method implemented within my own struct
// PublisherError as well is a custom Error.
// uri will be a string 
async fn _connect(&self) -> Result<Connection, PublisherError> {
    let uri = self.config.generate_uri();
    match Connection::connect(&uri, ConnectionProperties::default()).await {
        Ok(c) => Ok(c),
        Err(e) => {
            let err = PublisherError::new(...);
            Err(err)
        }
    }
}
```
The failures seem to happen during the handshake with the server, where the client is sending a `Connection.Open` frame before a `Connection.Tune-Ok` which forces the server to close the connection.
When the order is reversed, the connection gets established successfully.
I'm attaching a wireshark capture which shows the communication on both a successful and unsuccessful attempt to connect. I'm also attaching the trace logs from `lapin` for both cases, and the error that the rabbitmq server logs when the handshake fails.

Please let me know if there's anything else I can provide to help with the issue.

[logs.tar.gz](https://github.com/CleverCloud/lapin/files/6086870/logs.tar.gz)

**Comment by Keruspe** [comment]
Hi,

The traces should be enough.
How easily can you reproduce, and how good is your network?
I might know where this could come from, because of some network error, which should be fixed in 2.0, but not sure yet how to properly avoid this in 1.x

**Comment by konomith** [comment]
Hi, thanks for the answer.

> How easily can you reproduce, and how good is your network?  

I'm actually facing this issue on the same machine, connecting to `localhost`.  I get the connection error maybe once every 5-10 connection attempts. 

I forgot to mention that I'm on version `2.0.0-alpha.1`. I hadn't noticed that `2.0.0-alpha.2` was out, I'll test with that and see if the issue still exists.

**Comment by konomith** [comment]
It seems that the issue persists even after upgrading to `2.0.0-alpha.2`, with more or less the same rate.

**Comment by Keruspe** [comment]
Is this a --release build?

Logs are qui clear about the problem indeed, just trying to reproduce and haven't managed to (yet)

**Comment by Keruspe** [comment]
Scratch that, managed to reproduce now

**Comment by Keruspe** [comment]
Ok, so this was actually a regression in 2.0 alpha. the whole connection process is the part for which 2.0 is still in alpha stage are there are significant reworks pending

**Comment by konomith** [comment]
Thanks for the quick fix!
